#!/usr/bin/env python
import rospy
import numpy as np
import cv2
from sensor_msgs.msg import CompressedImage
# from scipy.ndimage import filters
import sys, time
import roslib
class image_feature:

    def __init__(self):
        '''Initialize ros publisher, ros subscriber'''
        # topic where we publish
        self.image_pub = rospy.Publisher("/image_raw/compressed",
            CompressedImage)
        # self.bridge = CvBridge()

        # subscribed Topic
        self.subscriber = rospy.Subscriber("/camera/image/compressed",
            CompressedImage, self.callback,  queue_size = 1)
        if VERBOSE :
            print "subscribed to /camera/image/compressed"


    def callback(self, ros_data):
        '''Callback function of subscribed topic. 
        Here images get converted and features detected'''
        if VERBOSE :
            print 'received image of type: "%s"' % ros_data.format

        #### direct conversion to CV2 ####
        np_arr = np.fromstring(ros_data.data, np.uint8)
        image_np = cv2.imdecode(np_arr, cv2.CV_LOAD_IMAGE_COLOR)
        
        #### Feature detectors using CV2 #### 
        # "","Grid","Pyramid" + 
        # "FAST","GFTT","HARRIS","MSER","ORB","SIFT","STAR","SURF"
        method = "GridFAST"
        feat_det = cv2.FeatureDetector_create(method)
        time1 = time.time()

        # convert np image to grayscale
        featPoints = feat_det.detect(
            cv2.cvtColor(image_np, cv2.COLOR_BGR2GRAY))
        time2 = time.time()
        if VERBOSE :
            print '%s detector found: %s points in: %s sec.'%(method,
                len(featPoints),time2-time1)

        for featpoint in featPoints:
            x,y = featpoint.pt
            cv2.circle(image_np,(int(x),int(y)), 3, (0,0,255), -1)
        
        cv2.imshow('cv_img', image_np)
        cv2.waitKey(2)

        #### Create CompressedIamge ####
        msg = CompressedImage()
        msg.header.stamp = rospy.Time.now()
        msg.format = "jpeg"
        msg.data = np.array(cv2.imencode('.jpg', image_np)[1]).tostring()
        # Publish new image
        self.image_pub.publish(msg)
        
        #self.subscriber.unregister()
        
      
def findFeatures(args):
    '''Initializes and cleanup ros node'''
    ic = image_feature()
    rospy.init_node('image_feature', anonymous=True)
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print "Shutting down ROS Image feature detector module"
    cv2.destroyAllWindows()
    
class CameraPublisher(object):
    
    def __init__(self):
        """OpenCV feature detectors with ros CompressedImage Topics in python.
        
        This example subscribes to a ros topic containing sensor_msgs 
        CompressedImage. It converts the CompressedImage into a numpy.ndarray, 
        then detects and marks features in that image. It finally displays 
        and publishes the new image - again as CompressedImage topic.
        """
        self.publisher = rospy.Publisher("/image_raw/compressed", CompressedImage, queue_size=4)
        self.msg = CompressedImage()
        
        rospy.loginfo('Setting camera level...')
        self.camera = cv2.VideoCapture(int(rospy.get_param('camera_port', 0)))
        
        self.takeImage(lightSettingSnaps=30)
        
    def takeImage(self, lightSettingSnaps=0):
        for i in range(lightSettingSnaps):
            self.takeImage(lightSettingSnaps=0)
        return self.camera.read()[1]
    
    def publishImage(self):
        image = self.takeImage()
        self.msg.header.stamp = rospy.Time.now()
        self.msg.format = "jpeg"
        self.msg.data = np.array(cv2.imencode('.jpg', image)[1]).tostring()
        # Publish new image
        self.publisher.publish(self.msg)
        
    def spin(self):
        r = rospy.Rate(rospy.get_param('imageRate', 10))
        idle = rospy.Rate(10)
        while not rospy.is_shutdown():
            self.publishImage()
            r.sleep()
            idle.sleep()

if __name__ == '__main__':
    rospy.init_node('cameraPublisher', log_level=rospy.DEBUG)
    cameraPublisher = CameraPublisher()
    cameraPublisher.spin()