#!/usr/bin/env python

from sys import argv
from os.path import basename
usage = 'USAGE %s [on|off] [stopOnExit]\n(Got argv: %s' % (basename(argv[0]), argv)
if len(argv) == 1:
    exit(usage)
cmd = argv[1].strip().lower()
if cmd == 'on':
    state = True
elif cmd == 'off':
    state = False
else:
    exit(usage)
    
stopOnExit = False
if len(argv) > 2 and argv[2].strip().lower() == 'stoponexit':
    stopOnExit = True
    

import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BOARD)
pin = 23
GPIO.setup(pin, GPIO.OUT)
GPIO.output(pin, state)

if stopOnExit:
    from time import sleep
    while True:
        try:
            sleep(1.0)
        except:
            break
    GPIO.output(pin, False)
    
